// Public SDK types — friendly aliases over the spec-derived `./generated/api.ts`
// (generated by openapi-typescript from openapi.yaml; wire format is the single source
// of truth). This shim renames spec types for SDK callers and assembles the hand-curated
// discriminated WebhookEvent union. Do NOT edit ./generated/api.ts — regen from the spec.

import type { components } from './generated/api';

type Schemas = components['schemas'];

// ── Currency / money ─────────────────────────────────────────────────

export type Currency = Schemas['Currency'];

// ── Order primitives ─────────────────────────────────────────────────

export type PaymentMethod = Schemas['PaymentMethod'];
export type OrderStatus = Schemas['OrderStatus'];
export type CanceledBy = Schemas['CanceledBy'];
export type CancelReasonCode = Schemas['CancelReasonCode'];
/** Pickup / dropoff waypoint — address + contact + coordinates.
 *  Same shape for create input and every read. */
export type Waypoint = Schemas['Waypoint'];
/** Waypoint on an Order — adds `completedAt` (when the driver marked
 *  this waypoint's phase done: pickup = picked up; dropoff = delivered). */
export type OrderWaypoint = Schemas['OrderWaypoint'];
/** Driver's live GPS on `Order.driver.currentLocation`. */
export type DriverLocation = NonNullable<
  NonNullable<Schemas['Order']['driver']>['currentLocation']
>;

/** Terminal outcome on `Order.financials.outcome`. Distinguishes the four
 *  cancel flavors (pre/post × driver/workspace) plus door refusal from a
 *  clean completion — narrow on this for outcome-specific handling. */
export type OrderOutcome = Schemas['Outcome'];

/** Sandbox scenarios accepted by `orders.create({ simulation })` /
 *  `orders.quote({ simulation })`. Live environment rejects with 400. */
export type SimulationScenario = NonNullable<Schemas['OrderCreate']['simulation']>;

// ── Requests ─────────────────────────────────────────────────────────

/** Body for `client.orders.create(input)`. Mirrors the
 *  `OrderCreate` schema in the spec. */
export type CreateOrderInput = Schemas['OrderCreate'];

/** Body for `client.orders.quote(input)`. */
export type QuoteInput = Schemas['QuoteRequest'];

/** Body for `client.orders.cancel(orderId, input?)`. All fields optional.
 *  `canceledBy` accepts `pickup` / `dropoff` / `workspace` (default) —
 *  audit-trail attribution only; `driver` / `system` are reserved and
 *  fall back to `workspace`. */
export type CancelOrderInput = Schemas['CancelOrderRequest'];

/** Body for `client.orders.rate(orderId, input)`. */
export type RateOrderInput = Schemas['RatingRequest'];

/** Optional query for `client.orders.list(input?)`. Hand-defined because
 *  query params don't get a top-level component schema in the spec —
 *  they're attached to the operation. `since` / `until` are inclusive
 *  YYYY-MM-DD bounds on `createdAt`; omit either side for unbounded. */
export interface ListOrdersInput {
  limit?: number;
  offset?: number;
  since?: string;
  until?: string;
}

// ── Finance request inputs ───────────────────────────────────────────

/** Optional query for `client.finance.overview(input?)`. */
export interface FinanceOverviewInput {
  /** ISO date `YYYY-MM-DD`. Filters to entries on or after this date.
   *  Use the start of your monthly close period for a per-month rollup. */
  since?: string;
}

/** Optional query for `client.finance.ledger(input?)` and
 *  `client.finance.settlements(input?)`. `since` / `until` are inclusive
 *  YYYY-MM-DD bounds on `createdAt`; omit either side for unbounded. */
export interface FinancePaginationInput {
  limit?: number;
  offset?: number;
  since?: string;
  until?: string;
}

/** Optional query for `client.finance.statement(input?)`.
 *  `entries` paginates via `limit`/`offset`; `openingBalance`,
 *  `closingBalance`, `total`, and `summary` are window-scoped and
 *  identical across every page in the same window. */
export interface StatementInput {
  /** ISO date `YYYY-MM-DD`. Defaults to 30 days before `toDate`. */
  fromDate?: string;
  /** ISO date `YYYY-MM-DD`. Defaults to today. */
  toDate?: string;
  /** Page size for `entries`. Default 50, max 200. */
  limit?: number;
  /** Rows to skip from the start of `entries`. Default 0. */
  offset?: number;
}

// ── Responses ────────────────────────────────────────────────────────

export type Order = Schemas['Order'];
export type Quote = Schemas['Quote'];
export type OrderListResponse = Schemas['OrderListResponse'];
export type RatingResponse = Schemas['RatingResponse'];
export type OrderFinancials = Schemas['OrderFinancials'];

// Finance responses.
export type BalanceResponse = Schemas['BalanceResponse'];
export type FinanceSummary = Schemas['FinanceSummary'];
export type FinanceOverview = Schemas['FinanceOverview'];
export type LedgerEntry = Schemas['LedgerEntry'];
export type LedgerEntryType = Schemas['LedgerEntryType'];
export type Settlement = Schemas['Settlement'];
export type SettlementDirection = Schemas['SettlementDirection'];
export type LedgerListResponse = Schemas['LedgerListResponse'];
export type SettlementListResponse = Schemas['SettlementListResponse'];
/** One line in `SettlementWithItems.items[]` — a single per-order
 *  ledger contribution that rolled into the settle. Tagged with
 *  `origin` and `type` so a consumer can filter their slice
 *  (e.g. `items.filter(i => i.origin === 'api')`). */
export type SettlementItem = Schemas['SettlementItem'];
/** Response of `client.finance.getSettlement(id)`. Contains the
 *  Settlement audit row + a flat array of per-order items that
 *  contributed to it. Used for line-by-line reconciliation when the
 *  webhook's `breakdown` totals aren't enough. */
export type SettlementWithItems = Schemas['SettlementWithItems'];
export type Statement = Schemas['Statement'];

// ── Workspace profile ────────────────────────────────────────────────

/** Response of `client.workspace.getProfile()` and `updateProfile(...)`.
 *  Sanitized — credentials never appear; `apiKeyLast4` is the only
 *  key-related field. */
export type WorkspaceProfile = Schemas['WorkspaceProfile'];
/** Body for `client.workspace.updateProfile(input)` — include only the
 *  fields you're changing. */
export type UpdateWorkspaceProfileInput = Schemas['UpdateWorkspaceProfileInput'];
export type WorkspaceIndustry = Schemas['WorkspaceIndustry'];
export type OperatingHours = Schemas['OperatingHours'];
/** Response of `client.workspace.rotateCredentials()`. `apiKey` is the
 *  new key — shown once, never retrievable again. */
export type RotateCredentialsResponse = Schemas['RotateCredentialsResponse'];
/** Response of `client.workspace.setWebhookUrl(url)`. */
export type SetWebhookUrlResponse = Schemas['SetWebhookUrlResponse'];

/** Fulfilment snapshot on `Order.fulfillment`. Discriminated on `kind`:
 *  `'platform'` (Altaer network, no identity exposed) or `'fleet'` (own fleet, carries id/name). */
export type Fulfillment = NonNullable<Order['fulfillment']>;
/** Driver block on `Order.driver` — null pre-assignment. */
export type OrderDriver = NonNullable<Order['driver']>;
/** Route + ETAs block on `Order.route`. */
export type OrderRoute = Order['route'];
/** Cancellation block on `Order.cancellation` — null unless canceled. */
export type OrderCancellation = NonNullable<Order['cancellation']>;
/** Return contract block on `Order.return` — always present. */
export type OrderReturn = Order['return'];
/** Buy-at-pickup block on `Order.buyAtPickup` — null unless enabled at create. */
export type OrderBuyAtPickup = NonNullable<Order['buyAtPickup']>;
/** Tracking block on `Order.tracking` — public share URL + raw token. */
export type OrderTracking = NonNullable<Order['tracking']>;
/** Payment block on `Order.payment` — method + amounts. */
export type OrderPayment = Order['payment'];

// ── Webhook event union ──────────────────────────────────────────────

/** Every webhook event type Altaer emits. Settlement events follow
 *  `workspace.<counterparty>_<balance_type>.<action>`; direction (in/out
 *  of workspace's books) is on the payload's `direction` field, not the event name. */
export type WebhookEventType =
  | 'order.created'
  | 'order.no_driver_found'
  | 'order.driver_assigned'
  | 'order.picked_up'
  | 'order.completed'
  | 'order.canceled'
  | 'order.failed'
  | 'order.rejected'
  // Workspace ↔ Altaer for platform delivery fees.
  | 'workspace.altaer_balance.settled'
  | 'workspace.altaer_balance.reversed'
  // Operator ↔ Altaer for fleet commission. Fans out per workspace
  // contributing to the operator's total commission settle.
  | 'workspace.altaer_fleet_commission.settled'
  | 'workspace.altaer_fleet_commission.reversed'
  // Operator ↔ workspace off-platform settle (record-only — Altaer
  // doesn't move money).
  | 'workspace.operator_fleet_balance.recorded'
  // Operator ↔ driver fleet-driver settle (record-only). Delivered to
  // the operator's own workspace so own-fleet integrations see driver payouts.
  | 'workspace.fleet_driver_balance.settled'
  | 'workspace.fleet_driver_balance.reversed'
  | 'fleet.created'
  | 'fleet.deleted'
  | 'fleet.driver.added'
  | 'fleet.driver.released'
  | 'fleet.driver.transferred'
  | 'fleet.trust.granted'
  | 'fleet.trust.revoked'
  | 'driver.kyc.status_changed';

/** Common envelope fields wrapping every event. The discriminator is
 *  `type`; narrow with `switch (event.type) { ... }`. */
export type WebhookEnvelope<T extends WebhookEventType, D> = Schemas['WebhookEnvelopeBase'] & {
  type: T;
  data: D;
};

// Generated allOf intersections — re-exported with predictable names.
export type FleetSnapshot = Schemas['FleetSnapshot'];
export type DriverSnapshot = Schemas['DriverSnapshot'];

// ── Altaer balance: workspace ↔ Altaer for platform delivery fees ──

/** Forward settle of workspace's delivery balance with Altaer. Read `breakdown.<origin>`
 *  for per-origin slice; positive = workspace owes platform, negative = platform owes workspace. */
export type AltaerBalanceSettledPayload = Schemas['AltaerBalanceSettledPayload'];

/** Reversal of a prior balance settle. `breakdown` is a sign-preserved copy of the
 *  original's — apply with inverse sign; forward + reversal cancel by construction. */
export type AltaerBalanceReversedPayload = Schemas['AltaerBalanceReversedPayload'];

/** Signed per-origin slice of a workspace-level money move. Same shape
 *  is reused on the settle / reversal payloads and on the audit
 *  Settlement row. */
export type OriginBreakdown = Schemas['OriginBreakdown'];

// ── Fleet commission: operator ↔ Altaer (per-workspace slice) ──────

/** One per-workspace slice of an operator's commission settle.
 *  Operators settle their total commission with one PSP charge;
 *  Altaer fans it out into N events (one per workspace contributing).
 *  All slices share `settlementId` and `providerRef`. */
export type AltaerFleetCommissionSettledPayload = Schemas['AltaerFleetCommissionSettledPayload'];

/** One per-workspace slice of a reversed commission settle. */
export type AltaerFleetCommissionReversedPayload = Schemas['AltaerFleetCommissionReversedPayload'];

// ── Operator ↔ workspace off-platform settle ──────────────────────

/** Record-only settle between operator and workspace (Altaer doesn't
 *  move money). Either side can record; `initiatedBy` distinguishes. */
export type OperatorFleetBalanceRecordedPayload = Schemas['OperatorFleetBalanceRecordedPayload'];

// ── Operator ↔ fleet driver settle (off-platform payout / COD collect) ──

/** Operator settled one of their fleet drivers off-platform.
 *  Record-only — Altaer doesn't move the money. `direction` is
 *  operator's POV (`paid_to` = payout; `collected_from` = COD collected). */
export type FleetDriverBalanceSettledPayload = Schemas['FleetDriverBalanceSettledPayload'];

/** Reversal of a prior fleet-driver settle. Rare — driver settles are
 *  typically cash. Join the forward via `originalSettlementId`. */
export type FleetDriverBalanceReversedPayload = Schemas['FleetDriverBalanceReversedPayload'];

// Fleet / driver / KYC payloads — extracted from their respective
// envelopes' `data` shape so partners can annotate variables against
// the same types the SDK passes to their handlers.
export type FleetCreatedPayload = Schemas['WebhookEnvelopeFleetCreated']['data'];
export type FleetDeletedPayload = Schemas['WebhookEnvelopeFleetDeleted']['data'];
export type FleetDriverAddedPayload = Schemas['WebhookEnvelopeFleetDriverAdded']['data'];
export type FleetDriverReleasedPayload = Schemas['WebhookEnvelopeFleetDriverReleased']['data'];
export type FleetDriverTransferredPayload =
  Schemas['WebhookEnvelopeFleetDriverTransferred']['data'];
export type FleetTrustGrantedPayload = Schemas['WebhookEnvelopeFleetTrustGranted']['data'];
export type FleetTrustRevokedPayload = Schemas['WebhookEnvelopeFleetTrustRevoked']['data'];
export type DriverKycStatusChangedPayload = Schemas['WebhookEnvelopeDriverKyc']['data'];

/** Discriminated union of every webhook event. Narrow with `switch (event.type)`. */
export type WebhookEvent =
  | WebhookEnvelope<'order.created', Order>
  | WebhookEnvelope<'order.no_driver_found', Order>
  | WebhookEnvelope<'order.driver_assigned', Order>
  | WebhookEnvelope<'order.picked_up', Order>
  | WebhookEnvelope<'order.completed', Order>
  | WebhookEnvelope<'order.canceled', Order>
  | WebhookEnvelope<'order.failed', Order>
  | WebhookEnvelope<'order.rejected', Order>
  | WebhookEnvelope<'workspace.altaer_balance.settled', AltaerBalanceSettledPayload>
  | WebhookEnvelope<'workspace.altaer_balance.reversed', AltaerBalanceReversedPayload>
  | WebhookEnvelope<
      'workspace.altaer_fleet_commission.settled',
      AltaerFleetCommissionSettledPayload
    >
  | WebhookEnvelope<
      'workspace.altaer_fleet_commission.reversed',
      AltaerFleetCommissionReversedPayload
    >
  | WebhookEnvelope<
      'workspace.operator_fleet_balance.recorded',
      OperatorFleetBalanceRecordedPayload
    >
  | WebhookEnvelope<'workspace.fleet_driver_balance.settled', FleetDriverBalanceSettledPayload>
  | WebhookEnvelope<'workspace.fleet_driver_balance.reversed', FleetDriverBalanceReversedPayload>
  | WebhookEnvelope<'fleet.created', FleetCreatedPayload>
  | WebhookEnvelope<'fleet.deleted', FleetDeletedPayload>
  | WebhookEnvelope<'fleet.driver.added', FleetDriverAddedPayload>
  | WebhookEnvelope<'fleet.driver.released', FleetDriverReleasedPayload>
  | WebhookEnvelope<'fleet.driver.transferred', FleetDriverTransferredPayload>
  | WebhookEnvelope<'fleet.trust.granted', FleetTrustGrantedPayload>
  | WebhookEnvelope<'fleet.trust.revoked', FleetTrustRevokedPayload>
  | WebhookEnvelope<'driver.kyc.status_changed', DriverKycStatusChangedPayload>;
